export const TYPES = {
    CREATE_BLOG: 'CREATE_BLOG',
    LIKES: 'LIKES',
    DISLIKES: 'DISLIKES',
    FETCH_BLOG_REQUEST: "FETCH_BLOG_REQUEST",
    FETCH_BLOG_SUCCESS: "FETCH_BLOG_SUCCESS",
    FETCH_BLOG_FAILURE: "FETCH_BLOG_FAILURE",
    POSTED_BLOG: 'POSTED_BLOG'
};

